'use strict';
const fs=require('node:fs');
const path=require('node:path');
const read=name=>fs.readFileSync(path.join(__dirname,name),'utf8');
let html=read('index.html');
html=html.replace(/<link rel="stylesheet" href="styles\.css(?:\?[^\"]*)?">/,()=>'<style>\n'+read('styles.css')+'\n</style>');
html=html.replace(/<script src="(?:engine|trial|levels|hints|tutorial|journey|results|economy|app)\.js(?:\?[^\"]*)?" defer><\/script>/g,'');
const js=['engine.js','trial.js','levels.js','hints.js','tutorial.js','journey.js','results.js','economy.js','app.js'].map(read).join('\n').replace(/<\/script/gi,'<\\/script');
html=html.replace('</body>',()=>'<script>\n'+js+'\n</script>\n</body>');
fs.copyFileSync(path.join(__dirname,'economy.js'),path.join(__dirname,'api','economy-rules.js'));
const output=path.resolve(__dirname,'dist','cat-sudoku.html');
fs.mkdirSync(path.dirname(output),{recursive:true});
fs.writeFileSync(output,html);
console.log('Created '+output);
