/* Route order, unit grouping and starter cats for all 162 puzzles.
 * GENERATED by plan-build.cjs from measured difficulty (see difficulty.js and DIFFICULTY.md).
 * Do not hand-edit: level ids are content hashes, so dropping or reordering one here would move
 * every player's saved progress. Change the planner and regenerate.
 */
(function(root){'use strict';
const config={
  "units": [
    {
      "name": "初次见面",
      "tag": "跟着提示走完第一关",
      "cap": 1,
      "lessons": [
        15
      ],
      "id": 0,
      "start": 0,
      "count": 20
    },
    {
      "name": "猫生旅途",
      "tag": "空盘自由推理 · 卡住就用提示",
      "cap": 3,
      "lessons": [],
      "id": 1,
      "start": 20,
      "count": 47
    },
    {
      "name": "大胆假设",
      "tag": "需要假设试错的关卡 · 教一次就会了",
      "cap": 5,
      "lessons": [
        13
      ],
      "id": 2,
      "start": 67,
      "count": 22
    },
    {
      "name": "截图还原",
      "tag": "按原截图还原",
      "cap": 5,
      "lessons": [],
      "id": 10,
      "start": 89,
      "count": 7,
      "testPack": true
    },
    {
      "name": "百关挑战 · 第 1 组",
      "tag": "7 × 7 · 空盘自由推理",
      "cap": 5,
      "lessons": [],
      "id": 11,
      "start": 96,
      "count": 20,
      "extraPack": true
    },
    {
      "name": "百关挑战 · 第 2 组",
      "tag": "8 × 8 · 空盘自由推理",
      "cap": 5,
      "lessons": [],
      "id": 12,
      "start": 116,
      "count": 20,
      "extraPack": true
    },
    {
      "name": "百关挑战 · 第 3 组",
      "tag": "8 × 8 · 空盘自由推理",
      "cap": 5,
      "lessons": [],
      "id": 13,
      "start": 136,
      "count": 20,
      "extraPack": true
    },
    {
      "name": "百关挑战 · 第 4 组",
      "tag": "9 × 9 · 空盘自由推理",
      "cap": 5,
      "lessons": [],
      "id": 14,
      "start": 156,
      "count": 20,
      "extraPack": true
    },
    {
      "name": "百关挑战 · 第 5 组",
      "tag": "9 × 9 · 空盘自由推理",
      "cap": 5,
      "lessons": [],
      "id": 15,
      "start": 176,
      "count": 20,
      "extraPack": true
    }
  ],
  "levels": [
    {
      "id": "garden-3577ffdbc2eaf39e",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-a2e4f5b129c094cf",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-25310f102bd2b40d",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-091b6df0cb6d8622",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-bb899edd51d058e8",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-afe5b25f0717f429",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-80be429b158a7a52",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-360693cf049a9c0a",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-e7958203d13b4970",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-d915327ad8ff592b",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-7934e02eb770bb40",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-38b7ebb6fecd21ec",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-165a94ffe3ba6dd2",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-de7839238a822d5a",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-76e3ef5127dc3df1",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-fc42eba6bbfb030c",
      "unit": 0,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-3457b7b792135f0e",
      "unit": 0,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-7827347e0d68b988",
      "unit": 0,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-dc131cc6cbc193e2",
      "unit": 0,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-2e463ae8f9bc2e52",
      "unit": 0,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-1af08f1cf40df0f1",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-a31ab9484050ff4a",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-de2560a1e675444d",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-055afbee7f871eed",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "window",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-ee4d255c0d3fd54e",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-8be1dfb6c448de5c",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-e3287375c8c2f421",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-ff83edc4f56f702b",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-2a033cb4756635b6",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-73077c1a4c16ab16",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-7855942a62f1ec32",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-96383ed219fbeaa0",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-0a7bd2f22c608a09",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-bafc638f0ebc40dd",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "yard",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-d417a67d879ee5d3",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-3be8d54661fd20dd",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-98eb04af57dca091",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-fc8b15cfa0e66cea",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-34d56e67bd11de16",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-b13511e0ed2d9c8f",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-fb2dd415d6ae15fb",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-b50142e7b974d5ac",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-b5d3d0acd10cb171",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-1eec98707609e75c",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-edfb322b86600f73",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-21fad6fb4f3969a4",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-3115bf95cf5253fa",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-d9d74fa7dace233b",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-a109eca0fd6574d2",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-309fe430550aa453",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-f216b6411fa48dcd",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-c4d0837d7b942822",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-3010253034b124ba",
      "unit": 1,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-cf97c8daccb30660",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-5f498ac8e49b7404",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-4737375cf5501ab6",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-f5c3bf2ce9d706fc",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-058f329fbf0af807",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-9e6f8cccb0db3819",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "roof",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-b15e5107d941c85a",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-3e4c609c58a3625c",
      "unit": 1,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-7cd24b1aa847aa25",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-f0326c0d5cd0de9c",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-04445c8fedb1ac63",
      "unit": 1,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-1dbc32e36cdd69e8",
      "unit": 2,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-e0ba14421c94e43b",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-77416539431c2ee2",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-60b622df826f1f96",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-c054590132eeaff4",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-297799ce663833fe",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-9abb69824e258e7d",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-8505e8c2a3c17da4",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-fa4500de172e184b",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-8e1e1ba86fa9c046",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "moon",
      "unit": 2,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-3a974caa82a3c19b",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-bc7b3b1bc504c500",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-4747d5d13c42d804",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-cc0529bba9389734",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-ba5bc6aa41efa8f1",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "stars",
      "unit": 2,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-4d77f8c659dcf3fd",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-efa8d73edcefe3a2",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-a5e79fac812aab64",
      "unit": 2,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-cd721a078ad43be4",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-37f7a7b9b2ccb6f3",
      "unit": 2,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "screenshot-89",
      "unit": 10,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "screenshot-79",
      "unit": 10,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "screenshot-75",
      "unit": 10,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "screenshot-78",
      "unit": 10,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "screenshot-80",
      "unit": 10,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "screenshot-74",
      "unit": 10,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "screenshot-81",
      "unit": 10,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-08f73375f7cbc30b",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-712fcbeaf79dbfb6",
      "unit": 11,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-e0bf94f467bc13df",
      "unit": 11,
      "givens": [],
      "difficulty": 2
    },
    {
      "id": "garden-744ec694eb051ab0",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-fce425edf2878184",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-0de455137b28f1dd",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-3db54027b7aeb849",
      "unit": 11,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-30cac10d1d8088e4",
      "unit": 11,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-12f9f89922555ebd",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-faea0758d36ce841",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-15cec2e40c401a9b",
      "unit": 11,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-46b9f379e9cb0193",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-f130f798538023dc",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-b6e68cd3b7443eaa",
      "unit": 11,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-024720f8e6e48d69",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-70501efda7b3995e",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-93f7c38ca94190b0",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-889ad5612a4c6710",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-0be306b097791739",
      "unit": 11,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-ce55a0f6ab1a5f79",
      "unit": 11,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-0d8223d03e4cc4b4",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-855c98a23e66cce0",
      "unit": 12,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-df044568cc5ac044",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-c577731ded185953",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-618a4043fe2e22ce",
      "unit": 12,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-ea484bb620ec7d4e",
      "unit": 12,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-264fcb437b47a3ca",
      "unit": 12,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-9a6a49b18edb374a",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-28ddabc39945bd80",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-ee1bf9d513737aef",
      "unit": 12,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-e43786427a239b5b",
      "unit": 12,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-fea28129ed875d7e",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-9a77ab2032850901",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-b26f6e00fc1417fe",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-026c3e85b68e2772",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-6b87dfdf9340ef98",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-d2937d958052ba17",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-e99a8e1a69ccf932",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-9caf062ab353d8bb",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-cb136c62208d59ad",
      "unit": 12,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-2f9ef4a9ff1df50a",
      "unit": 13,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-329990fe89eca04d",
      "unit": 13,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-b141fdd225e8df03",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-a3b6818561592aae",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-898343bc5172847f",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-f948023738634001",
      "unit": 13,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-1f0ddb5bcc56fd2d",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-bddb27a01d4ae7ed",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-5298829dcbb1d5dc",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-83f3032581a21a6f",
      "unit": 13,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-0745656126e11de2",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-08244f933aa31b5f",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-9dc635bb79cb8090",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-b6a1dd1648960f54",
      "unit": 13,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-773a4ae52c4795d7",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-359549e4b6fedd8d",
      "unit": 13,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-746e5718a88979f5",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-9232fd7cc7e0986f",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-7e9e13e83a06b47d",
      "unit": 13,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-c1a154f4be5b3d82",
      "unit": 13,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-5b4f82419b87e689",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-19731ef0f018e315",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-4dba4e0b469742ed",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-438909d67a7b63d8",
      "unit": 14,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-99503cf8a4795c73",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-fda6f0a262ed853e",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-a81ab4ea1e84e031",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-5ec80cf8e9d3bcf4",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-dbae7d81faa5042b",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-251fcfe4fccaeda9",
      "unit": 14,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-c55c51ada6b3e689",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-f0de50a9d256e378",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-0ed87ccbc3d3cbb8",
      "unit": 14,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-ea9da77739c2a57b",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-032e017ca23ff0b9",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-3ad89c5153c0ab7b",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-39db0448af01d90e",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-49e2bcb736301a66",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-e0a08f93a2b0b840",
      "unit": 14,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-5335583b2d85fc88",
      "unit": 14,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-bfc6277030d59994",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-1dd01f69058c731c",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-9c27e64328a7e16e",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-68c6175d3062946b",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-2ccb7747f277243b",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-5462b5763f41d724",
      "unit": 15,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-1583279dcc69f9fa",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-67956ade627bc2ee",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-bd27226860f2dc86",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-fdd8b78d15476d07",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-1d4c3d7e6d8566f6",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-a8733bccbc4defa8",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-ec067c1b0939c325",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-53a4dc8880956939",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-d767449b4fee4a5d",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-d716e51a8b2a8074",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    },
    {
      "id": "garden-a50232e497fc50ae",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-1f3ef556f1a02b2c",
      "unit": 15,
      "givens": [],
      "difficulty": 4
    },
    {
      "id": "garden-1ae7f42570523338",
      "unit": 15,
      "givens": [],
      "difficulty": 5
    },
    {
      "id": "garden-8b331ac281685931",
      "unit": 15,
      "givens": [],
      "difficulty": 3
    }
  ]
};
// The table above is generated by plan-build.cjs from measured difficulty - see DIFFICULTY.md.
// Edit the planner, not this file: level ids are content hashes, so a hand-edit that drops or
// reorders an id silently moves a player's progress. `start` is informational only; the order in
// `levels` is the order the player walks.
const UNIT_IDS=new Set(config.units.map(u=>u.id));
config.levels.forEach(entry=>{if(!UNIT_IDS.has(entry.unit))throw Error('关卡 '+entry.id+' 指向不存在的单元 '+entry.unit);});
function arrange(levels){const byId=new Map(levels.map(l=>[l.id,l]));return [...config.levels.flatMap(c=>byId.has(c.id)?[byId.get(c.id)]:[]),...levels.filter(l=>!config.levels.some(c=>c.id===l.id))];}
function forLevel(level){const entry=config.levels.find(c=>c.id===level.id);const expansion=level.expansion;const pack=expansion?.pack==='more-100-20261004'&&Number.isInteger(expansion.group)&&expansion.group>=1&&expansion.group<=5?10+expansion.group:null;const unit=pack!==null&&config.units.some(u=>u.id===pack)?pack:1;return entry||{id:level.id,unit,givens:[],difficulty:3};}
function startBoard(level){const given=forLevel(level).givens;return Array.from({length:level.size**2},(_,i)=>given.includes(i)?2:0);}
function unitFor(level){return config.units.find(u=>u.id===forLevel(level).unit)||config.units[1];}
// Difficulty is 2-5 cats, rated against the other boards of the same size (see difficulty.js).
// Generated in plan-build.cjs; a level with no rating falls back to the middle of the scale.
function difficultyFor(level){const value=forLevel(level).difficulty;return Number.isInteger(value)&&value>=2&&value<=5?value:3;}
const DIFFICULTY_TEXT={2:'轻松',3:'适中',4:'偏难',5:'很难'};
// Completed ids that no longer match a level are kept in `stale` instead of being dropped. Garden
// level ids are content hashes, so regenerating the level data would otherwise erase a player's
// history without a trace; `completed` still counts only live levels, so the readouts stay honest.
function validProgress(raw,levels){
  const ids=new Set(levels.map(l=>l.id));
  const done=(Array.isArray(raw?.completed)?raw.completed:[]).filter(id=>typeof id==='string'||typeof id==='number');
  return{
    completed:[...new Set(done.filter(id=>ids.has(id)))],
    learned:[...new Set((Array.isArray(raw?.learned)?raw.learned:[]).filter(id=>UNIT_IDS.has(id)))],
    stale:[...new Set(done.filter(id=>!ids.has(id)))],
    current:ids.has(raw?.current)?raw.current:levels[0].id
  };
}
const api={config,arrange,forLevel,startBoard,unitFor,difficultyFor,DIFFICULTY_TEXT,validProgress};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.CatJourney=api;
})(typeof globalThis!=='undefined'?globalThis:this);
