'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),R=require('./results.js');
const source=fs.readFileSync(__dirname+'/app.js','utf8');
let now=0,modal=false,g={started:false,elapsed:0,paused:false,won:false};
const display={textContent:''},document={hidden:false,body:{dataset:{view:'home'}}};
const context={performance:{now:()=>now},game:()=>g,R,document,modalOpen:()=>modal,$:()=>display,time:ms=>String(ms),lastTick:0};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function tick(){'),source.indexOf("function record(kind='move')")),context);
const advance=ms=>{now+=ms;context.tick();};
advance(5000);assert.equal(g.elapsed,0,'home does not count');
document.body.dataset.view='game';advance(2500);assert.equal(g.elapsed,2500,'fresh untouched board must count immediately');assert.equal(g.started,false,'no first-click state required');
g.started=true;advance(500);assert.equal(g.elapsed,3000,'first action neither starts nor resets the clock');
g.paused=true;advance(2000);assert.equal(g.elapsed,3000);g.paused=false;
modal=true;advance(2000);assert.equal(g.elapsed,3000);modal=false;
document.hidden=true;advance(2000);assert.equal(g.elapsed,3000);document.hidden=false;
document.body.dataset.view='home';advance(2000);assert.equal(g.elapsed,3000);
document.body.dataset.view='game';advance(1000);assert.equal(g.elapsed,4000);
g={started:false,elapsed:0,paused:false,won:false};advance(1000);assert.equal(g.elapsed,1000,'next/reset/replay board needs no move');
g.won=true;advance(5000);assert.equal(g.elapsed,1000,'completed time is immutable');
const historical={id:'historical',levelId:'level-1',elapsedMs:12345,hints:0,conflicts:0,guides:0};
const saved=JSON.stringify(historical);R.summarize({...historical,id:'new',elapsedMs:20000},[historical]);assert.equal(JSON.stringify(historical),saved);
console.log('PASS immediate untouched-board timing, first-click continuity, pause/menu/home/background, fresh next/reset/replay and unchanged completed times');
